name: "Fire event if log file updated"
on: 
        workflow_run:
                workflows: ["Update log file after push"]
                types: [completed]
jobs:
        fire-event:
                runs-on: ubuntu-latest
                if: ${{ github.event.workflow_run.conclusion == 'success' }}
                steps:
                        - uses: actions/checkout@v2
                        - uses: dorny/paths-filter@v2 # will create filters for changed files
                          id: filter-log-data
                          with:
                                  filters: >
                                          log: 
                                            - 'file.log'
                                          json:
                                            - 'file.json'

                        - name: "Fire event if update"
                          if: steps.filter-log-data.outputs.log == 'true'
                          run: echo "Log file has been updated recently !"

                        - name: "Fire event if JSON file update"
                          if: steps.filter-log-data.outputs.json == 'true'
                          run: echo "json file has been updated recently !"


